# Generated by Django 5.0 on 2023-12-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_person_sex_alter_hotel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', "I don't want to answer")], default='M', max_length=1),
        ),
    ]
