# Generated by Django 5.0 on 2023-12-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_person_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Not selected', "I don't want to answer")], default='Not selected', max_length=12),
        ),
    ]
