# Generated by Django 5.0 on 2023-12-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_person_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='max_persons',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
